# Generated by Django 3.0.7 on 2023-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20220812_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubIpList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=200)),
                ('ips', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
