# Generated by Django 3.0.7 on 2023-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_subiplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subiplist',
            name='ext',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
