# Generated by Django 3.0.7 on 2023-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_subiplist_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainlist',
            name='is_assign',
            field=models.BooleanField(default=False),
        ),
    ]
