# Generated by Django 3.0.7 on 2023-03-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_projectannouncement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
