# Generated by Django 3.0.7 on 2023-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_project_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='extra',
        ),
    ]
