# Generated by Django 3.0.7 on 2023-03-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20230327_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsource',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
