# Generated by Django 3.0.7 on 2023-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True, unique=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('head_url', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('verify', models.CharField(blank=True, max_length=255, null=True)),
                ('spider_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wechat_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatAccountTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
                ('last_publish_time', models.DateTimeField(blank=True, null=True)),
                ('last_spider_time', models.DateTimeField(blank=True, null=True)),
                ('is_zombie', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wechat_account_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
                ('digest', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('pics_url', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('spider_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wechat_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('is_top', models.IntegerField(blank=True, null=True)),
                ('spider_time', models.DateTimeField(blank=True, null=True)),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
            ],
            options={
                'db_table': 'wechat_article_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatArticleDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('read_num', models.IntegerField(blank=True, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('spider_time', models.DateTimeField(blank=True, null=True)),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
            ],
            options={
                'db_table': 'wechat_article_dynamic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('digest', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.IntegerField(blank=True, null=True)),
                ('is_multi', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_stat', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('sn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('spider_time', models.DateTimeField(blank=True, null=True)),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
            ],
            options={
                'db_table': 'wechat_article_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatArticleTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('article_url', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('field_biz', models.CharField(blank=True, db_column='__biz', max_length=50, null=True)),
            ],
            options={
                'db_table': 'wechat_article_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WechatProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=100, null=True)),
                ('value', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wechat_article_task',
                'managed': False,
            },
        ),
    ]
