# Generated by Django 3.0.7 on 2023-04-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wechatprofile',
            table='wechat_profile',
        ),
    ]
