# Generated by Django 3.0.7 on 2023-05-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20230421_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=2000)),
                ('type', models.IntegerField(default=0)),
                ('last_scan_time', models.DateTimeField(auto_now=True)),
                ('wait_time', models.IntegerField(default=600)),
                ('flag', models.CharField(default=None, max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'botend_monitortask',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'botend_monitorwebhook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('cookie', models.TextField(null=True)),
                ('is_login', models.BooleanField(default=True)),
                ('ext', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'botend_targetauth',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WechatAccount',
        ),
        migrations.DeleteModel(
            name='WechatArticleComment',
        ),
        migrations.DeleteModel(
            name='WechatArticleDynamic',
        ),
        migrations.DeleteModel(
            name='WechatArticleList',
        ),
        migrations.DeleteModel(
            name='WechatArticleTask',
        ),
        migrations.DeleteModel(
            name='WechatProfile',
        ),
        migrations.AlterModelTable(
            name='wechataccounttask',
            table='botend_wechataccounttask',
        ),
        migrations.AlterModelTable(
            name='wechatarticle',
            table='botend_wechatarticle',
        ),
    ]
