# Generated by Django 3.0.7 on 2022-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_frontlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='last_scan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontlog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
