# Generated by Django 3.0.7 on 2023-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20221213_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('config_data', models.TextField(null=True)),
                ('is_display', models.BooleanField(default=False)),
            ],
        ),
    ]
