# Generated by Django 3.0.7 on 2023-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_configdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdata',
            name='ext',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
